"""empty message

Revision ID: 0ed27f9ab13a
Revises: 61fd262f5a6e
Create Date: 2019-08-15 21:45:44.522676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed27f9ab13a'
down_revision = '61fd262f5a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('attendant_name', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('date_sold', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sale_id', name=op.f('pk_sales'))
    )
    op.create_index(op.f('ix_sales_attendant_name'), 'sales', ['attendant_name'], unique=False)
    op.create_index(op.f('ix_sales_customer_name'), 'sales', ['customer_name'], unique=False)
    op.create_index(op.f('ix_sales_date_sold'), 'sales', ['date_sold'], unique=False)
    op.create_index(op.f('ix_sales_product_name'), 'sales', ['product_name'], unique=False)
    op.create_index(op.f('ix_sales_product_price'), 'sales', ['product_price'], unique=False)
    op.create_index(op.f('ix_sales_quantity'), 'sales', ['quantity'], unique=False)
    op.create_index(op.f('ix_sales_total_price'), 'sales', ['total_price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_total_price'), table_name='sales')
    op.drop_index(op.f('ix_sales_quantity'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_price'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_name'), table_name='sales')
    op.drop_index(op.f('ix_sales_date_sold'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_name'), table_name='sales')
    op.drop_index(op.f('ix_sales_attendant_name'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
