"""empty message

Revision ID: 61fd262f5a6e
Revises: 9df738b790a5
Create Date: 2019-08-15 21:36:10.742678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61fd262f5a6e'
down_revision = '9df738b790a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_category_name'), 'categories', ['category_name'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('stock_amount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('low_inventory_stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_low_inventory_stock'), 'products', ['low_inventory_stock'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_index(op.f('ix_products_stock_amount'), 'products', ['stock_amount'], unique=False)
    op.drop_index('ix_Products_category_id', table_name='Products')
    op.drop_index('ix_Products_low_inventory_stock', table_name='Products')
    op.drop_index('ix_Products_price', table_name='Products')
    op.drop_index('ix_Products_product_name', table_name='Products')
    op.drop_index('ix_Products_stock_amount', table_name='Products')
    op.drop_table('Products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('product_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Products_product_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low_inventory_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_id', name='pk_Products')
    )
    op.create_index('ix_Products_stock_amount', 'Products', ['stock_amount'], unique=False)
    op.create_index('ix_Products_product_name', 'Products', ['product_name'], unique=False)
    op.create_index('ix_Products_price', 'Products', ['price'], unique=False)
    op.create_index('ix_Products_low_inventory_stock', 'Products', ['low_inventory_stock'], unique=False)
    op.create_index('ix_Products_category_id', 'Products', ['category_id'], unique=False)
    op.drop_index(op.f('ix_products_stock_amount'), table_name='products')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_low_inventory_stock'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_categories_category_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
