"""empty message

Revision ID: 9df738b790a5
Revises: 2fc8487febe3
Create Date: 2019-08-15 21:32:14.225531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df738b790a5'
down_revision = '2fc8487febe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('stock_amount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('low_inventory_stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_Products'))
    )
    op.create_index(op.f('ix_Products_category_id'), 'Products', ['category_id'], unique=False)
    op.create_index(op.f('ix_Products_low_inventory_stock'), 'Products', ['low_inventory_stock'], unique=False)
    op.create_index(op.f('ix_Products_price'), 'Products', ['price'], unique=False)
    op.create_index(op.f('ix_Products_product_name'), 'Products', ['product_name'], unique=False)
    op.create_index(op.f('ix_Products_stock_amount'), 'Products', ['stock_amount'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Products_stock_amount'), table_name='Products')
    op.drop_index(op.f('ix_Products_product_name'), table_name='Products')
    op.drop_index(op.f('ix_Products_price'), table_name='Products')
    op.drop_index(op.f('ix_Products_low_inventory_stock'), table_name='Products')
    op.drop_index(op.f('ix_Products_category_id'), table_name='Products')
    op.drop_table('Products')
    # ### end Alembic commands ###
